#!/bin/bash

set -xe

export GOPATH=$PWD/go
export PATH=$GOPATH/bin:$PATH

go get github.com/tools/godep
go get golang.org/x/tools/cmd/cover
source_dir="$(cd "$(dirname "$0")" && pwd)"
cd $source_dir/..
godep go test ./... -v -cover -race
