#!/bin/bash

set -xe

export GOPATH=$PWD/go
export PATH=$GOPATH/bin:$PATH

go get github.com/tools/godep
source_dir="$(cd "$(dirname "$0")" && pwd)"
cd $source_dir/..
cd cmd/concourse-demo-app
godep go build .
